project:
  type: website
  output-dir: _site
  
format:
  html:
    theme: minty
    css: styles.css
    toc: true
    citeproc: true

website:
  title: "Chen Lab"
  site-url: "https://www.kennethchenlab.com/"
  search: true

  navbar:
    brand: "CHEN LAB"
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research/index.qmd
      - text: Publications
        href: publications/index.qmd
      - text: Members
        href: members/index.qmd
      - text: Contact
        href: contact.qmd

  page-footer:
    left: |
      © 2019–present Chen Lab
    right:
      - icon: github
        href: https://github.com/kennethchenlab

execute:
  echo: false
  warning: false
  message: false
  freeze: auto
  
jupyter: false
