[build]
  command = "quarto render"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.5.57"

[context.production.environment]
  NETLIFY_USE_QUARTO = "true"
  
[[plugins]]
package = "@quarto/netlify-plugin-quarto"